"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useContext, useState, createContext } from "react";

export const ThemeContext = createContext();

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState("Dark");
  const themeValue = useContext(ThemeContext);

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      <html
        lang="en"
        className={`${theme === "Dark" ? "bg-slate-950  text-white" : ""}`}
      >
        <head>
          <title>News App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeContext.Provider>
  );
}
